//load('database.js')
var db = new Mongo().getDB('CognizantCityATX');
var candidatesExist = db.getCollection('Candidates').exists();
if(!candidatesExist) {
    db.createCollection("Candidates");

    db['Candidates'].insert([
        {
            "election_id":"general",
            "district":0,
            "position":"mayor",
            "name":"Steve Adler",
            "focus":"new 10-1 system, traffic, affordability, public education, poverty, water, environment",
            "image":"\/images\/steve_adler.jpg",
            "experience":"chief of staff\/general counsel for state Sen. Eliot Shapleigh; attorney (has argued civil rights cases, focuses on eminent domain defense); Anti-Defamation League Austin Region board chair; Texas Tribune board chair",
            "occupation":"attorney",
            "facebook":"http:\/\/facebook.com\/adlerforaustin",
            "url":"http:\/\/www.adlerforaustin.com\/",
            "contact":"@AdlerForAustin",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":0,
            "position":"mayor",
            "name":"Sheryl Cole",
            "focus":"Affordability, transportation, water, diversity, equity",
            "image":"\/images\/sheryl_cole.jpg",
            "experience":"Three-term City Council member; attorney and CPA; public schools advocate (former PTA president)",
            "occupation":"Mayor Pro Tem",
            "facebook":"http:\/\/www.facebook.com\/SherylforAustin",
            "url":"http:\/\/www.sherylforaustin.com\/ ",
            "contact":"@SherylCole1",
            "in_office":1,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":0,
            "position":"mayor",
            "name":"Mike Martinez",
            "focus":"affordability, traffic and transportation, equity",
            "image":"\/images\/mike_martinez.jpg",
            "experience":"longtime civic activist; former firefighter and president, Austin Firefighters Association; Capital Metro board member and current chair",
            "occupation":"City Council member (since 2006)",
            "facebook":"http:\/\/facebook.com\/MikeMartinezforAustin ",
            "url":"http:\/\/www.mike4mayor.com\/ ",
            "contact":"@CouncilManMike",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":0,
            "position":"mayor",
            "name":"Todd Phelps",
            "focus":"transportation, environmental protection, taxation, open space",
            "image":"\/images\/todd_phelps.jpg",
            "experience":"energy negotiations, lending projects, farming, ranching, property management; arts and film production",
            "occupation":"musician; businessman",
            "facebook":"http:\/\/facebook.com\/toddphelpsmusic ",
            "url":"http:\/\/www.phelpsforaustin.com\/ ",
            "contact":"@PhelpsForAustin",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":7,
            "position":"council member",
            "name":"Jimmy Paver",
            "focus":"transportation, affordability, fiscal values",
            "image":"\/images\/jimmy_paver.jpg",
            "experience":"former congressional (Rep. Lloyd Doggett) and state House (Rep. Mark Strama) aide",
            "occupation":"",
            "facebook":"http:\/\/facebook.com\/jimmypaverforaustin",
            "url":"http:\/\/www.jimmypaverforaustin.com\/",
            "contact":"",
            "in_office":0,
            "finance":"",
            "other":"$40,000 loan taken out for political expend."
        },
        {
            "election_id":"general",
            "district":7,
            "position":"council member",
            "name":"Melissa Zone",
            "focus":"neighborhood preservation, affordability, transportation, health & safety, environmental protection",
            "image":"\/images\/melissa_zone.jpg",
            "experience":"transportation and water resource planner; co-author, Colorado River Corridor Plan; legislative analysis; public engagement and outreach",
            "occupation":"senior urban planner, Travis County",
            "facebook":"",
            "url":"http:\/\/www.zoneforaustin.com\/",
            "contact":"",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":8,
            "position":"council member",
            "name":"Becky Bray",
            "focus":"transportation, fiscal responsibility, affordability, water",
            "image":"\/images\/becky_bray.jpg",
            "experience":"board member, Real Estate Council of Austin; Capital Area Transportation Coalition; Greater Austin Chamber of Commerce",
            "occupation":"project manager, Brown & Gay Engineers",
            "facebook":"",
            "url":"",
            "contact":"",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":8,
            "position":"council member",
            "name":"Eliza May",
            "focus":"pending",
            "image":"\/images\/eliza_may.jpg",
            "experience":"longtime civic activist",
            "occupation":"public policy consultant",
            "facebook":"",
            "url":"",
            "contact":"",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":8,
            "position":"council member",
            "name":"Darrell Pierce",
            "focus":"efficiency, basic services, affordability, economic diversity",
            "image":"\/images\/darrell_pierce.png",
            "experience":"former state agency administrator (General Services Commission); Council candidate (2006); city commissioner (Planning Commission, Transit Working Group); civic volunteer",
            "occupation":"president and CEO, SNAP Management consulting firm",
            "facebook":"http:\/\/facebook.com\/DarrellPierceforAustin",
            "url":"http:\/\/www.darrellpierce.com\/",
            "contact":"",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":8,
            "position":"council member",
            "name":"Ed Scruggs",
            "focus":"affordability, open space\/parks, protecting Southwest Austin",
            "image":"\/images\/ed_scruggs.jpg",
            "experience":"neighborhood advocate; civic activist; former Circle C HOA director",
            "occupation":"clinical research associate",
            "facebook":"http:\/\/facebook.com\/Edscruggs4Austin8",
            "url":"http:\/\/www.edscruggsfordistrict8.org\/",
            "contact":"https:\/\/twitter.com\/Ed4Austin8",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":9,
            "position":"council member",
            "name":"Erin McGann",
            "focus":"transportation infrastructure, livability, simplified regulation, business\/education volunteerism",
            "image":"\/images\/erin_mcgann.jpg",
            "experience":"Citizens Review Panel (Office of Police Monitor); professional work in human services and public safety; basic needs coordination",
            "occupation":"program supervisor (community re-entry), Texas Dept. of Criminal Justice",
            "facebook":"http:\/\/facebook.com\/pages\/Erin-McGann-Austin-District-9\/651060658264855",
            "url":"",
            "contact":"erin4district9@gmail.com, @Erindistrict9",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":9,
            "position":"council member",
            "name":"Chris Riley",
            "focus":"economy & environment; transportation; preserving Austin's character (affordability, art, human services)",
            "image":"\/images\/chris_riley.jpg",
            "experience":"Council membership; city commissioner (Planning Commission, Downtown Commission, etc.); co-founder and former president, Downtown Austin NA",
            "occupation":"City Council member (since 2009); attorney",
            "facebook":"http:\/\/facebook.com\/ChrisForAustin",
            "url":"http:\/\/www.chrisforaustin.com\/",
            "contact":"chris@chrisforaustin.com",
            "in_office":1,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":9,
            "position":"council member",
            "name":"Kathie Tovo",
            "focus":"affordability, neighborhood schools, transportation",
            "image":"\/images\/kathie_tovo.jpg",
            "experience":"Council membership; former president, Bouldin Creek NA; former vice president, Austin Neighborhoods Council; city commissioner (Planning Commission, Families and Children Task Force, etc.); Austin ISD Committee on Neighborhoods and Schools",
            "occupation":"City Council member (since 2011)",
            "facebook":"http:\/\/https\/\/www.facebook.com\/kathieforaustin?notif_t=fbpage_fan_invite",
            "url":"http:\/\/www.kathieforaustin.com\/",
            "contact":"https:\/\/twitter.com\/kathietovo",
            "in_office":1,
            "finance":"$1,912",
            "other":""
        },
        {
            "election_id":"general",
            "district":10,
            "position":"council member",
            "name":"Margie Burciaga",
            "focus":"transportation, property crime control, taxation, affordability",
            "image":"\/images\/margie_burciaga.jpg",
            "experience":"schools advocate; neighborhood organization member; Leadership Austin member",
            "occupation":"business owner, Image Consulting Austin",
            "facebook":"",
            "url":"www.margieburciaga.com",
            "contact":"",
            "in_office":0,
            "finance":"$557",
            "other":""
        },
        {
            "election_id":"general",
            "district":10,
            "position":"council member",
            "name":"Tina Cannon",
            "focus":"property tax appraisals, water and conservation, emergency preparedness (wildfires), affordability, transportation",
            "image":"\/images\/tina_cannon.jpg",
            "experience":"Council candidate (2012); entrepreneur-in-residence (Texas State Univ.); financial auditor and business consultant",
            "occupation":"partner, Napkin Venture (entrepreneur advisory firm); director of client relations, Tuggey Calvoz law firm",
            "facebook":"http:\/\/facebook.com\/ElectTinaCannon",
            "url":"www.tinacannon.org",
            "contact":"http:\/\/www.tinacannon.org\/contact_us",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":10,
            "position":"council member",
            "name":"Mandy Dealey",
            "focus":"water, transportation, affordability, neighborhood preservation",
            "image":"\/images\/mandy_dealey.jpg",
            "experience":"city commissioner (Planning Commission, Waterfront Overlay, etc.); former board chair, Mental Health Association, Planned Parenthood, Texas Lyceum, and Preservation Austin; current chair of KMFA-FM",
            "occupation":"civic activist",
            "facebook":"http:\/\/facebook.com\/MandyDealey10",
            "url":"www.mandydealey.com",
            "contact":"",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":10,
            "position":"council member",
            "name":"Sheri Gallo",
            "focus":"transportation and mobility, affordability and taxation, water (drought and wildfires), core services (public safety and infrastructure)",
            "image":"\/images\/sheri_gallo.png",
            "experience":"Commissioners Court candidate (2002); former chair, Housing Authority of Austin; former board member, Real Estate Council of Austin",
            "occupation":"Realtor, business owner (Private Properties agency)",
            "facebook":"https:\/\/www.facebook.com\/sherigalloaustincitycouncil",
            "url":"http:\/\/www.sherigallo.com\/",
            "contact":"http:\/\/www.sherigallo.com\/contact_us",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":10,
            "position":"council member",
            "name":"Matt Lamon",
            "focus":"district representation, transportation infrastructure, efficiency, cost of living",
            "image":"\/images\/matt_lamon.jpg",
            "experience":"legislative staffer",
            "occupation":"chief of staff, state Rep. J.M. Lozano (R-Kingsville)",
            "facebook":"",
            "url":"http:\/\/www.mattlamon.com\/",
            "contact":"https:\/\/twitter.com\/matthewlamon",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":10,
            "position":"council member",
            "name":"Robert Thomas",
            "focus":"transportation, taxation, affordability",
            "image":"\/images\/robert_thomas.jpg",
            "experience":"state House candidate, HD48 (2012)",
            "occupation":"business consultant",
            "facebook":"http:\/\/facebook.com\/VoteRobertThomas",
            "url":"",
            "contact":"",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":0,
            "position":"mayor",
            "name":"Steve Adler",
            "focus":"new 10-1 system, traffic, affordability, public education, poverty, water, environment",
            "image":"\/images\/steve_adler.jpg",
            "experience":"chief of staff\/general counsel for state Sen. Eliot Shapleigh; attorney (has argued civil rights cases, focuses on eminent domain defense); Anti-Defamation League Austin Region board chair; Texas Tribune board chair",
            "occupation":"attorney",
            "facebook":"http:\/\/facebook.com\/adlerforaustin",
            "url":"http:\/\/www.adlerforaustin.com\/",
            "contact":"@AdlerForAustin",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":0,
            "position":"mayor",
            "name":"Sheryl Cole",
            "focus":"Affordability, transportation, water, diversity, equity",
            "image":"\/images\/sheryl_cole.jpg",
            "experience":"Three-term City Council member; attorney and CPA; public schools advocate (former PTA president)",
            "occupation":"Mayor Pro Tem",
            "facebook":"http:\/\/www.facebook.com\/SherylforAustin",
            "url":"http:\/\/www.sherylforaustin.com\/ ",
            "contact":"@SherylCole1",
            "in_office":1,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":0,
            "position":"mayor",
            "name":"Mike Martinez",
            "focus":"affordability, traffic and transportation, equity",
            "image":"\/images\/mike_martinez.jpg",
            "experience":"longtime civic activist; former firefighter and president, Austin Firefighters Association; Capital Metro board member and current chair",
            "occupation":"City Council member (since 2006)",
            "facebook":"http:\/\/facebook.com\/MikeMartinezforAustin ",
            "url":"http:\/\/www.mike4mayor.com\/ ",
            "contact":"@CouncilManMike",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":0,
            "position":"mayor",
            "name":"Todd Phelps",
            "focus":"transportation, environmental protection, taxation, open space",
            "image":"\/images\/todd_phelps.jpg",
            "experience":"energy negotiations, lending projects, farming, ranching, property management; arts and film production",
            "occupation":"musician; businessman",
            "facebook":"http:\/\/facebook.com\/toddphelpsmusic ",
            "url":"http:\/\/www.phelpsforaustin.com\/ ",
            "contact":"@PhelpsForAustin",
            "in_office":0,
            "finance":"",
            "other":""
        },
        {
            "election_id":"general",
            "district":0,
            "position":"mayor",
            "name":"Randall Stephens",
            "focus":"campaign finance reform, transportation, small business development, short term rental rates",
            "image":"\/images\/randall_stephens.jpg",
            "experience":"Air Force veteran",
            "occupation":"air-craft mechanic, tech entrepreneur (CEO of AdBirds website)",
            "facebook":"facebook.com\/StephensForAustin",
            "url":"stephensforaustinmayor.org",
            "contact":"@AustinBlueDog",
            "in_office":0,
            "finance":null,
            "other":null
        }
    ]);
}